"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

import { createClient } from "@/lib/supabase/client";
import type { NotificationItem } from "@/types";

/**
 * Reads and updates Supabase directly rather than going through the
 * FastAPI backend — these rows are already scoped to auth.uid() by RLS
 * (see supabase/migrations/0001_init.sql), so a service-role backend hop
 * would only add risk (either leaking every user's notifications or
 * needing to re-verify the JWT) without adding anything. The backend's
 * POST /api/notifications/refresh still generates these rows on a
 * schedule — this page only reads and marks them read.
 */
export default function NotificationsPage() {
  const [items, setItems] = useState<NotificationItem[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [needsLogin, setNeedsLogin] = useState(false);

  useEffect(() => {
    const supabase = createClient();

    supabase.auth.getUser().then(({ data }) => {
      if (!data.user) {
        setNeedsLogin(true);
        return;
      }

      supabase
        .from("notifications")
        .select("*")
        .order("created_at", { ascending: false })
        .limit(30)
        .then(({ data: rows, error: fetchError }) => {
          if (fetchError) setError(fetchError.message);
          else setItems(rows as NotificationItem[]);
        });
    });
  }, []);

  async function markRead(id: string) {
    const supabase = createClient();
    await supabase.from("notifications").update({ read: true }).eq("id", id);
    setItems((prev) => prev?.map((n) => (n.id === id ? { ...n, read: true } : n)) ?? null);
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="font-display text-2xl font-medium text-ink">Notifications</h1>
        <p className="mt-1 text-sm text-muted">
          Curve inversions, AI decision changes, and upcoming high-impact releases.
        </p>
      </div>

      <section className="rounded border border-border bg-panel p-5">
        {needsLogin && (
          <p className="text-sm text-muted">
            <Link href="/login" className="text-gold hover:underline">
              Log in
            </Link>{" "}
            to see your notifications.
          </p>
        )}
        {error && <p className="text-sm text-negative">{error}</p>}
        {!needsLogin && !error && items === null && <p className="text-sm text-muted">Loading…</p>}
        {!needsLogin && !error && items && items.length === 0 && (
          <p className="text-sm text-muted">
            No notifications yet — they're generated by{" "}
            <code className="font-mono text-ink">POST /api/notifications/refresh</code> whenever
            there's something to report (a curve inversion, an AI decision change, or a
            high-impact release in the next day).
          </p>
        )}
        {!needsLogin && !error && items && items.length > 0 && (
          <ul className="space-y-3">
            {items.map((item) => (
              <li
                key={item.id}
                className={`flex items-start justify-between gap-3 border-b border-border pb-3 last:border-0 ${
                  item.read ? "opacity-50" : ""
                }`}
              >
                <div>
                  <div className="text-sm text-ink">{item.title}</div>
                  {item.body && <div className="mt-0.5 text-xs text-muted">{item.body}</div>}
                </div>
                {!item.read && (
                  <button
                    onClick={() => markRead(item.id)}
                    className="shrink-0 text-xs text-gold hover:underline"
                  >
                    Mark read
                  </button>
                )}
              </li>
            ))}
          </ul>
        )}
      </section>
    </div>
  );
}
